# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0004_auto_20170825_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_favourite',
            new_name='is_favorite',
        ),
    ]
